<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_All</name>
   <tag></tag>
   <elementGuidId>ad852e1e-4248-46c4-a5b0-312aa1a50039</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nav-hamburger-menu</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='nav-hamburger-menu']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6b254d86-5dcb-4b42-bf65-b974d9db7b45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript: void(0)</value>
      <webElementGuid>fcaf73c3-622e-4ac2-90a5-9569d142bce4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-hamburger-menu</value>
      <webElementGuid>7a3fa734-8f6d-4aee-9ea8-dc0ba2d0dd47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>18448b75-3809-443e-a7f5-7b7f055319db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Open Menu</value>
      <webElementGuid>0ffd5a99-b4b8-47d7-9290-395c9f52b805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-type</name>
      <type>Main</type>
      <value>widget</value>
      <webElementGuid>571fa7bb-501c-423c-8759-3dad246bdea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-slot-id</name>
      <type>Main</type>
      <value>HamburgerMenuDesktop</value>
      <webElementGuid>2afd085d-2c20-4b69-aeb9-6654f20ef7dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-interaction-events</name>
      <type>Main</type>
      <value>click</value>
      <webElementGuid>0b555b6b-9e84-452b-b263-47107e350b80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-id</name>
      <type>Main</type>
      <value>8fl0d2-xk0zht-9rba17-k9tued</value>
      <webElementGuid>5eae32d6-fb5b-4cbb-8543-9b50cd7e740a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
    
    All
  </value>
      <webElementGuid>1ca35a1b-11bd-4950-83c3-6a1456954d8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-hamburger-menu&quot;)</value>
      <webElementGuid>04d6433b-7df8-4238-a71e-479bbe2f617f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='nav-hamburger-menu']</value>
      <webElementGuid>a5a7ad3a-591b-4bc4-a81e-0229fff34f57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-main']/div/a</value>
      <webElementGuid>8caf6e37-0b3a-43e2-953c-7894de45974a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript: void(0)')]</value>
      <webElementGuid>ebdb5dda-a18e-418e-892b-d7b685052599</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/a</value>
      <webElementGuid>952a78f6-9aa1-48ce-af7e-a79da266a3e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript: void(0)' and @id = 'nav-hamburger-menu' and (text() = '
    
    All
  ' or . = '
    
    All
  ')]</value>
      <webElementGuid>7e36eaa9-3ab4-4881-a355-62280d5d64e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
